language: node_js
node_js:
 - "stable"

cache: 
  directories: 
    - "node_modules"

env:
    global:
      - CC_TEST_REPORTER_ID=42541f94fc6978e16ef2643e72662fc7f38e5072049d3164b2e0598151a30093
before_script:
  - npm i nyc --save-dev
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - nyc --reporter=lcov --reporter=text-lcov npm test

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

after_success: npm run coveralls
after_fail: npm run coverage
